# Generated by Django 3.2.18 on 2023-02-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Keycloak ID'),
        ),
    ]
