# Generated by Django 4.2 on 2024-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_keycloak', '__first__'),
        ('user', '0002_user_keycloak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_groups',
            field=models.ManyToManyField(blank=True, help_text='The keycloak groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='garpix_keycloak.keycloakgroup', verbose_name='keycloak groups'),
        ),
    ]
